### ISSUE TITLE
Enforce versioning guideline by CI checks

### ISSUE THREAD

**Issue by leogr** [falcosecurity/rules#13]
**Motivation**

Currently, the [versioning guidelines](https://github.com/falcosecurity/rules/blob/main/RELEASE.md) need to be manually checked and applied by maintainers, which is an error-prone process.

Also, see my [comment here](https://github.com/falcosecurity/rules/pull/12#pullrequestreview-1253473922).

cc @falcosecurity/falco-maintainers 

**Feature**

Enforce [versioning guidelines](https://github.com/falcosecurity/rules/blob/main/RELEASE.md) using the CI.

One possible solution would be to automatically add a label indicating the type of change (major, minor, patch) to incoming PRs. In this way, it will be immediately clear to the release manager which version number must be bumped when git tagging.

**Alternatives**

**Additional context**

_Off-topic_
A similar approach could be used in libs too since we have a similar problem with internal version numbers (ie. DRIVER_VERSION and SCHEMA_VERSION)
cc @falcosecurity/libs-maintainers

**Comment by jasondellaluce** [comment]
The label-based approach seems interesting. Another way could be to introduce a custom release note syntax (like we use to do for Falco).

The approach that I would prefer the most would be for Falco to "dump" (in a machine-readable format) all the definitions loaded in a given rules file and being able to apply all/most of the versioning guidelines automatically. This also matches the request of issues such as https://github.com/falcosecurity/falco/issues/1814, which still want Falco to dump its rules internal knowledge for ease of debugging and development. Just an idea, maybe not attainable, but would be cool.

**Comment by jasondellaluce** [comment]
This is now accomplished.

/close
