### ISSUE TITLE
[Discussion] Formalize Mitre tagging criteria and guidelines

### ISSUE THREAD

**Issue by incertum** [falcosecurity/rules#130]
**Discussion**

Information about the MITRE phases has been included in Falco rules' tags for a while. More recently, TTP (Tactics, Techniques, and Procedures) tags were added. The initial iteration, mostly completed by myself, was not very optimal. As part of the recent rules cleanup, I changed it to include only one phase and one TTP per detection.

However, I would like to start a discussion about this. Should we limit the use of MITRE phases and TTP codes to just one per rule, or should we consider allowing multiple phases and codes in certain cases?

---

For instance, I have sought feedback from Red Teamers, and here are some potential adjustments we could consider:

Results of a quick spot check, not all rules were audited:

> - Drop and execute new binary in container
>   - Suggestions: Stage Capabilities, https://attack.mitre.org/techniques/T1608/
> - Execution from /dev/shm
>   - Suggestions
>       - Defense Evasion, https://attack.mitre.org/tactics/TA0005/
>       - In some cases where /dev/shm is actually shared between separate Docker containers, or the host and container, e.g. https://docs.openshift.com/container-platform/3.11/dev_guide/shared_memory.html
> 	 - Persistence (because /dev/shm won't be cleared even on container restart)
> 	 - Lateral movement - /dev/shm is essentially a bridge to the host or other containers in this case, which opens up vectors to attack them, too.
>          - Context: On fileless malware: https://linuxsecurity.com/features/fileless-malware-on-linux
> 
> - Unexpected outbound connection destination
>    - Other possible tags: Exfiltration, Lateral movement

In addition I have received the following questions:

> How do you envision people will use these tags? What's the value of having them? How will they help defense/response teams?

My response would be that it assists adopters in evaluating the coverage and scope of Falco rule detections. Additionally, it can be seen as having educational value, aiding in understanding what a rule aims to detect and thus guiding the development of the appropriate incident response runbook. Keeping this in mind, incorporating multiple phases and TTP codes could be beneficial. However, including an excessive number of Mitre phases and TTP codes per rule is likely to have the opposite effect and might lead to confusion, particularly for those unfamiliar with the subject.

Related:

This is related to https://github.com/falcosecurity/rules/issues/88, but more around choosing the right tags in the first place.

**Comment by IceManGreen** [comment]
Hello Incertum,

I can bring some feedback from discussions with SOC analysts and operators on CTI products :
- We agree on the educational value that Mitre ATT&CK is a powerfull framework for learning about TTPs
- We agree on its efficiency to evaluate the coverage of rules detections on a system
- It is usually better to help a human to write detection rules with tools than automatize the entire process

In this case, I think that limiting Falco rules tags with one tactic phase is a good idea to reduce the risk of misinterpretations of alerts. Furthermore, it should make the writer of a rule aware of his context and write down the proper tactic phase for its rule.
In this case, the module `mitre-checker` is a good tool to help.

Finally, in the best case scenario, I think that the ideal would be to start from the Mitre ATT&CK framework, select TTPs and automatize the writing of Falco rules, based on system calls, with the supervision of a human.
I think it is a great topic, I would love to discuss about it with anyone interested in it and I am ready to contribute to projects that try to solve this problem :)
