### ISSUE TITLE
Consider adding a yaml-linter for the rules files

### ISSUE THREAD

**Issue by incertum** [falcosecurity/rules#144]
**Motivation**

Consider adding a yaml-linter for the rules files, see @Andreagit97 suggestion https://github.com/falcosecurity/rules/pull/142/files#r1308818842. This may help to enforce the new rules style guide consistently.

**Comment by h4l0gen** [comment]
Hey @incertum , @Andreagit97 . I am interested in this issue, can you please tell me more about it. Thanks!

**Comment by incertum** [comment]
Amazing @h4l0gen - we haven't discussed any ideas. Hence we are open to suggestions and recommendations! Thanks for taking this on!

**Comment by incertum** [comment]
> yamllint

It has [GPL-3.0 license](https://github.com/adrienverge/yamllint/blob/master/LICENSE) which requires a license exception with the CNCF. Could we find a project that has CNCF approved licenses?

```
- BSD-2-Clause
- BSD-2-Clause-FreeBSD
- BSD-3-Clause
- MIT
- ISC
- Python-2.0
- PostgreSQL
- X11
- Zlib
- Google patent license for Golang (https://golang.org/PATENTS)
all these + Apache2 are ok
```

CC @leogr

**Comment by h4l0gen** [comment]
@incertum we can consider this one https://github.com/CICDToolbox/yaml-lint?tab=readme-ov-file it has MIT license. please take a look.

**Comment by leogr** [comment]
> @leogr @incertum, if you both agree on using GitHub Actions, I would like to proceed by writing a YAML file.

ok :+1:
