### ISSUE TITLE
Container information

### ISSUE THREAD

**Issue by ajinkya1986** [falcosecurity/rules#184]
Currently all the rules in falco have `%container.info` field in the output parameters, which populates only limited container information. Is it possible to add more container information for the rule which require them. Like `container.image`, `container.image.id`, `container.type`, `container.image.tag` etc

**Comment by incertum** [comment]
See https://falco.org/docs/rules/style-guide/ string search for `%contaienr.info` to find the relevant paragraph.

Since you have this question I am wondering how we can improve the documentation in this regards. Would you have ideas?

**Comment by ajinkya1986** [comment]
This refers to creating new rules and adding container information. But how can we add more container information in the existing rules without creating custom rules.

**Comment by incertum** [comment]
Hi @ajinkya1986 no worries. The formatting guidelines apply to any rules you pass to Falco.

Have you tried https://falco.org/docs/outputs/formatting/?

Alternatively (if the special `%container.info` placeholder is not ideal for your use case) you can manually change the `output` yaml property in the existing rule(s) files and specifically define any field you want to be in the logs https://falco.org/docs/reference/rules/supported-fields/#field-class-container.
