### ISSUE TITLE
Remove k8s.gcr.io reference after 01/Dec/2023

### ISSUE THREAD

**Issue by ossie-git** [falcosecurity/rules#199]
**Describe the bug**

Not sure if this is a bug but while looking at  `rules/falco-sandbox_rules.yaml` I noticed the following comment and noticed that `k8s.gcr.io` has not been removed

```yaml
# TODO: Remove k8s.gcr.io reference after 01/Dec/2023
- list: user_known_k8s_ns_kube_system_images
  items: [
    k8s.gcr.io/fluentd-gcp-scaler,
    k8s.gcr.io/node-problem-detector/node-problem-detector,
    registry.k8s.io/fluentd-gcp-scaler,
    registry.k8s.io/node-problem-detector/node-problem-detector
  ]
```

**How to reproduce it**

**Expected behaviour**

**Screenshots**

**Environment**

- Falco version:

- System info:

- Cloud provider or hardware configuration:
- OS:

- Kernel:

- Installation method:

**Additional context**

**Comment by incertum** [comment]
Great catch @ossie-git, would you want to open a PR? happy to approve.

**Comment by incertum** [comment]
/remove-lifecycle stale

PR is up.
