### ISSUE TITLE
Helpful remove_sensitive_file_rule 

### ISSUE THREAD

**Issue by cccsss01** [falcosecurity/rules#220]
**What to document**
failed_remove_sensitive_file condition

similiar to the open sensitive file condition, just a failed or removed sensitive file condition would be much appreciated.

/kind documentation

**Comment by Andreagit97** [comment]
ei @cccsss01 sorry but I don't get what you mean, could you be a bit more specific? thanks

**Comment by cccsss01** [comment]
similar to open_read_failed, remove_file_failed would notify when an attempted deletion occurs.
