### ISSUE TITLE
Invalid engine_version_semver key in latest rules package

### ISSUE THREAD

**Issue by loresuso** [falcosecurity/rules#225]
**Describe the bug**

The newly released package for the Falco rules contains a semver version of 0.0.0
```
falcoctl artifact config falco-rules | jq 
{
  "name": "falco-rules",
  "version": "3.0.0",
  "requirements": [
    {
      "name": "engine_version_semver",
      "version": "0.0.0"
    }
  ]
}
```

Together with @leogr we spotted the bug. I'll open a PR soon to fix it.

**How to reproduce it**

**Expected behaviour**

**Screenshots**

**Environment**

- Falco version:

- System info:

- Cloud provider or hardware configuration:
- OS:

- Kernel:

- Installation method:

**Additional context**

```[tasklist]
### Tasks
- [ ] https://github.com/falcosecurity/rules/pull/226
- [x] Republish artifacts
```

**Comment by leogr** [comment]
We will need to re-release (or repuplish) 3.0.0 artifacts with the correct configuration.

/assign
/assign @LucaGuerra

**Comment by LucaGuerra** [comment]
released
