### ISSUE TITLE
Missed bump of Falco engine version

### ISSUE THREAD

**Issue by loresuso** [falcosecurity/rules#28]
**Describe the bug**

As described in https://github.com/falcosecurity/falco/pull/2418, we missed incrementing FALCO_ENGINE_VERSION for the latest Falco release. https://github.com/falcosecurity/rules/pull/20 is the first PR taking advantage of one of the newly introduced fields and should bump the `required_engine_version` to its proper number, which would be 16.  However, since we have `falcoctl` that is now able to follow new rules, extra care should be taken: a Falco 0.34.0 ingesting the new rules containing the one that we are introducing in PR #20, will fail to restart since it is stuck at version 15. 
A possible way to avoid this is to properly tag rules in a way that the new ones are not downloaded. Since in the Helm charts we are following tag 0, I think a bump of the major is needed.

**Comment by leogr** [comment]
I agree with the proposed solution.

/kind bug

I'm assigning this to 
/milestone falco-rules-0.2

However, if we agree to switch to 1.0.0 (and leave the 0.x untouched with this non-addressable issue), I will rename just rename the milestone.

cc @falcosecurity/rules-maintainers

**Comment by loresuso** [comment]
With the release of the version of the rules 1.0.0, this issue can be considered addressed. Closing.
