### ISSUE TITLE
Busybox triggers "Non sudo setuid" rule when running under unknown uid

### ISSUE THREAD

**Issue by shauser** [falcosecurity/rules#29]
**Describe the bug**

When running any busybox applet with an unregistered uid, the `Non sudo setuid` rule is triggered. This is caused by busybox calling `setresuid(-1, uid, uid)` on startup of every applet (see [source](https://github.com/mirror/busybox/blob/526625bc83e63e6e5a3ec5296a1b868e72b3b01e/libbb/appletlib.c#L570)). While these containers should probably run as nobody, it is a very common occurrence that containers run under a random uid which might not have been registered in the passwd file.

Edit: Same problem should appear with any user which is not hard-coded in the macro.

I would argue that changing the `somebody_becoming_themselves` macro to test for `evt.arg.uid=user.uid` would be a better test than the current implementation which tries to match a few hard-coded usernames. However, this seems to be impossible since `evt.arg.uid` is set to `<NA>` and there doesn't seem to be a way to get the actual `uid_t` value from the syscall in the falco rule. Or is there anything I am missing here?

**How to reproduce it**

`docker run --user 1234:1234 busybox:1.36.0 id` should trigger it, although I currently don't have falco on my local dev machine.

On k8s this can be used to reproduce it: `kubectl run -it --image=busybox:1.36.0 tmp -- bash` then `setuidgid 1234:1234 id`.

**Expected behaviour**

The rule should not trigger if the current `RUID` is equal to `evt.arg.uid` even if the current user is not one of the hard-coded ones or if the uid is not in `/etc/passwd`.

**Environment**

- Falco version: 0.33.1
- System info: machine=x86_64 release=5.4.0-1060-gkeop sysname=Linux version=#64-Ubuntu SMP
- Cloud provider or hardware configuration: GKE / Anthos Hybrid for VMWare
- OS: Ubuntu 20.04
- Kernel: 5.4.0-1060.64-gkeop
- Installation method: kubernetes with helm chart

**Comment by leogr** [comment]
cc @loresuso @darryk10
