### ISSUE TITLE
Publish artifact to S3

### ISSUE THREAD

**Issue by leogr** [falcosecurity/rules#4]
**Motivation**

See https://github.com/falcosecurity/falco/blob/master/proposals/20221129-artifacts-distribution.md#http-distribution
Required to use rules package in the Falco cmake.

**Feature**

**Alternatives**

**Additional context**

**Comment by leogr** [comment]
We need to delete the git tag and release it again to make this work after the fix introduced by #16

**Comment by LucaGuerra** [comment]
will do.

**Comment by LucaGuerra** [comment]
done! https://download.falco.org/?prefix=rules/
