### ISSUE TITLE
Make the build tool return the OCI artifact digest

### ISSUE THREAD

**Issue by maxgio92** [falcosecurity/rules#63]
**Motivation**

Signature of the OCI artifact will need the digest of the OCI artifact.

**Feature**

Introduce the return of the OCI artifact digest, when building and publishing the rules artifacts:

```
$ build/registry/rules-registry push-to-oci registry.yaml ${{ github.ref_name }}
<digest>
```

**Alternatives**

NA

**Additional context**

Please read the discussion about signature and signature verification of Falco artifacts, [here](https://github.com/falcosecurity/falcoctl/issues/174#issuecomment-1499338972).

**Comment by incertum** [comment]
Same question here, how can we unblock the open PRs? Thank you!
