### ISSUE TITLE
Sign the OCI artifact with cosign

### ISSUE THREAD

**Issue by maxgio92** [falcosecurity/rules#65]
**Motivation**

This feature request is part of a work which aims to improve the security of the Falco artifacts supply chain.

**Feature**

Introduce a step in the release pipeline which signs the rules OCI artifact built, with [cosign](https://github.com/sigstore/cosign).

**Alternatives**

Use different tools, like [Notary](https://github.com/notaryproject/notation), that provide different format, even though supporting same storage type (OCI Artifact). 

**Additional context**

In detail, of signatures of Falco OCI artifacts, you can read [here](https://github.com/falcosecurity/falcoctl/issues/174#issuecomment-1499338972).

**Comment by incertum** [comment]
@maxgio92 I see lots of PRs open ❤️ , what do you need from us to get them over the finish line? I am probably not the right person to review them, but wanted to ask anyways 🙃

**Comment by maxgio92** [comment]
Hey @incertum, I think TL;DR the order is:
- https://github.com/falcosecurity/plugins/pull/296
- #66 
- and for verification: https://github.com/falcosecurity/falcoctl/pull/305
