### ISSUE TITLE
Validation and integration test for rules

### ISSUE THREAD

**Issue by leogr** [falcosecurity/rules#8]
**Motivation**

The default Falco ruleset is currently tested in the Falco repository.

**Feature**

Implement CI checks to test incoming PR in this repository.
Basically, we have to move the relevant testing logic from the Falco repo to here.

**Alternatives**

**Additional context**

**Comment by jasondellaluce** [comment]
This is now addressed. What's missing is an in-depth and granular e2e testing suite for each rule similar to what we have in the event generator, but that must be described and addressed in another issue.
