### ISSUE TITLE
[Discussion] Creation and tagging of PCI DSS Falco rules

### ISSUE THREAD

**Issue by incertum** [falcosecurity/rules#95]
**Motivation**

As we are outlining clear use cases for Falco in the upcoming Falco 0.36 release, I am opening this ticket to discuss details around tagging PCI DSS Falco rules.

From the planned rules maturity and adoption proposal: 
> Adopters will be presented with clear primary use cases to better understand how Falco can be leveraged. These use cases will encompass "Threat Detection" and "Compliance". Rules specifically related to compliance will be tagged with TBD in the existing tag list.
>
> Falco serves two main use cases:
> - Threat Detection: Rule violations as indicators of compromise.
> - Compliance: Detecting unauthorized changes to files under PCI/DSS.

**Feature**

Agree on a standard to tag PCI DSS related rules and tag rules accordingly, ideally add new PCI DSS related rules as well.

**Additional context**

Part of the planned revamp of Falco's rules and maturity framework.

**Comment by incertum** [comment]
https://github.com/falcosecurity/falco-website/pull/1027#discussion_r1254660821 @n1g3ld0ugla5 we could use this ticket for discussing?

Also for everyone here is the published blog post https://falco.org/blog/falco-pci-controls/

It's also related to discussions around improving the Mitre tagging, see https://github.com/falcosecurity/rules/issues/88 as I did a first pass tagging of all rules and some Mitre tags are wrong or suboptimal, hence we should re-visit each rules tags in general as we audit all rules once we agree on the new formal rules maturity and adoption framework.

**Comment by leogr** [comment]
What's the status of this?

**Comment by incertum** [comment]
This should be addressed, forgot to close it. Thanks @leogr!
