### ISSUE TITLE
Wrong config safe_etc_dirs in falco_rules.yaml

### ISSUE THREAD

**Issue by karkill** [falcosecurity/rules#97]
**Describe the bug**

I get many errors `Write below etc` with prometheus-config-reloader, I think some missing with this config
```yaml
- list: safe_etc_dirs
  items: [/etc/cassandra, /etc/ssl/certs/java, /etc/logstash, /etc/nginx/conf.d, /etc/container_environment, /etc/hrmconfig, /etc/fluent/configs.d. /etc/alertmanager]
```
Please fix it with 
```yaml
- list: safe_etc_dirs
  items: [/etc/cassandra, /etc/ssl/certs/java, /etc/logstash, /etc/nginx/conf.d, /etc/container_environment, /etc/hrmconfig, /etc/fluent/configs.d, /etc/alertmanager]
 ```
If you have time, please check `/etc/fluent/configs.d`, I think it should be `/etc/fluent/config.d`

- Falco version: **0.35.1**
- Installation method: **Kubernetes**

**Comment by openJT** [comment]
I was having an issue with this also, /etc/alertmanager was not being ignored and had to override it entirely. I am a bit surprised nobody else reported this.
